# Netlify Configuration for Fluffy Bites
[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

# Custom domain configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Fotos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Logo/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SEO and user experience
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://fluffybites.net/*"
  to = "https://fluffybites.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.fluffybites.net/*"
  to = "https://fluffybites.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.fluffybites.net/*"
  to = "https://fluffybites.net/:splat"
  status = 301
  force = true

